### ISSUE TITLE
HP: Clicking "View All Work" should reveal the full work list (after the Work page loads).

### ISSUE THREAD

**Issue by jsonin** [goinvo/goinvo.com-2018#83]
On the home page, 
I click "view all work" under the 4 examples.

The Work page loads and shows 4 examples.
If I clicked a "view all" link, it should view all, ie expand all the goodies.

**Comment by sel2sm** [comment]
We wanted it to take you to the Work page and expand all of the case studies. 

Take you to the Work page - so that you can explore all of the categories with the special menu
Expand all of the case studies - because if it just takes you to the work page, you'll see the same 4 case studies. 

.... It could even scroll past the banner photo so your starting view is All the case studies...

@craigmcginley - can we do that? @jsonin is that satisfactory?

**Comment by jsonin** [comment]
Or by default, on the work page, since people are there to see the work, it's defaulted all open (so never any "view all" orange button.
?

**Comment by craigmcginley** [comment]
@sel2sm show all work all the time? or keep the "view all" button?

**Comment by sel2sm** [comment]
If the user clicks View All on the home page - the Work page should open with all open

If the user comes from anywhere else - I think it makes sense to keep it closed to 4. The user may just be browsing, and we have some helpful content like "Get in touch" underneath the case studies that they may otherwise never get to.

**Comment by craigmcginley** [comment]
done in 4c3788944bdf3d9f2a1ffb703f9a8dede33461ec
